[env:esp32dev]
platform = espressif32@3.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0

board_build.partitions = no_ota.csv

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -Os

lib_deps =
    https://github.com/bblanchon/ArduinoJson.git#v5.13.5
    ESP32 BLE Arduino
